db_path: "db/CH_wat_04_dev"
tel_storage_path: "db/CH_wat_04_dev/tel"
public_url: "http://localhost:4055/"
seed: "Alntkt3u6dDgiQxTATr01dy8M72uuaZEf9eTdM-70Gcc"
http_port: 4055
initial_oobis: [
  {
    "eid": "BHWp2RC0DcASYNWix4ln8LMaTmsJLlEEDGodGFdk3DsK",
    "scheme": "http",
    "url": "http://localhost:4043/"
  },
  {
    "eid": "BKi9A_efzy5tQv8OEuo-zSHamigGmQ6PW147KsspLATe",
    "scheme": "http",
    "url": "http://localhost:4044/"
  },
  {
    "eid": "BH5lwtC7sNefgsiUOYnlkiZ31vTirx5aiwB_CfdBWYB3",
    "scheme": "http",
    "url": "http://localhost:4045/"
  },
  {
    "eid": "BFvE03fcIi1WpCJFasELVUeJKKK1Aj0hw261LJhMYrWX",
    "scheme": "http",
    "url": "http://localhost:4046/"
  },
  {
    "eid": "BFg6ehxH_iyYleiApcBj3u1DgSPo8PQuzi4SBCn8BnIL",
    "scheme": "http",
    "url": "http://localhost:4047/"
  },
  {
    "eid": "BAo3EIXNe02xsxnAM4SgWKNixeybKDjP-c2u1P9e3QO0",
    "scheme": "http",
    "url": "http://localhost:4048/"
  }
]
escrow_config:
  default_timeout: 60
